### ISSUE TITLE
Uncaught TypeError: block.getText is not a function Draft 0.10.0

### ISSUE THREAD

**Issue by StevenIseki** [draft-js-plugins/draft-js-plugins#584]
I am trying to use Draft 0.10.0 with Draft-js-Plugins because I want some of the newer features on Draft including support for importing from html with images.

I get the following error with draft-js-plugins when I use for example the [image-plugin](https://www.draft-js-plugins.com/plugin/image) just the default code from this example

`Uncaught TypeError: block.getText is not a function at MultiDecorator.getDecorations`

**Comment by mzbac** [comment]
@StevenIseki   I think current draft-js-plugin only supports up to draft-js 0.9.1 version. no sure if there is any api level changes in the draft-js 0.10.0. could you please try to downgrade to 0.9.1? see if it works?

**Comment by StevenIseki** [comment]
@mzbac Thanks I guess it is a bit of a breaking change to keep an eye on for when `0.10.0` comes out, the way draft-js-plugins decorators are added to the Editor might need an update when it is released. Of course all is working in `0.9.1` and as that is the latest published version, I am happy to close this issue for now.
