### PR TITLE
Add some typescript typings

### PR DESCRIPTION
**Pull request by dobesv**
Add typescript typings for the core components and some of the plugins.

This can serve as a starting point for adding types to the other
plugins.

### CODE REVIEW

**Comment by juliankrispel** [comment]
@dobesv if you'd like to contribute more get in touch and I'll give you access :+1:

**Comment by gencer** [comment]
`id` and `editorState` are missing in typescript. Is this an expected behavior? If so, any docs?

**Comment by TrySound** [comment]
@gencer Could you point us where exactly?

**Comment by juliankrispel** [comment]
@gencer make sure you have `@types/draft-js` installed

**Comment by gencer** [comment]
@TrySound after i upgrade to v3.x, TypeScript complains about `id` and `editorState` are not a member of `Editor`.

@juliankrispel, Both installed:

```
Type '{ id: string; editorState: any; onChange: (editorState: any) => void; keyBindingFn: (e: any) => "enter" | "undo" | "redo" | "delete" | "delete-word" | "backspace" | "backspace-word" | "backspace-to-start-of-line" | ... 10 more ... | "secondary-paste"; plugins: any[]; placeholder: string; ref: (element: PluginEditor)...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.ts(2322)
```

To replicate in typescript:
```
              <Editor
                id={`composer-id-${isEdit ? message.id : "main"}`} // error 1
                editorState={this.state.editorState} // error 2
                onChange={this.onChange}
                keyBindingFn={this.keyBindingFn}
                plugins={this.plugins}
                placeholder={"Write comment..."}
                ref={(element) => { this.editor = element }}
              />

**Comment by dobesv** [comment]
Good issue reporting helps get you answers:

1. You should open a new issue since this PR is merged and closed
2. Please in that issue list off what versions of @types/draft-js and all the package versions for the plugins editor, etc..

**Comment by JoyNop** [comment]
> Good issue reporting helps get you answers:
> 
> 1. You should open a new issue since this PR is merged and closed
> 2. Please in that issue list off what versions of @types/draft-js and all the package versions for the plugins editor, etc..

**DraftJS Mention Plugin**
