### ISSUE TITLE
v3: Property `id` and `editorState` does not exist on type definitions

### ISSUE THREAD

**Issue by gencer** [draft-js-plugins/draft-js-plugins#1329]
After I upgrade my editor to v3.x, TypeScript complains about `id` and `editorState` are not members of `Editor`.

I've installed latest version of `@types/draft-js` (`0.10.35`).

```
Type '{ id: string; editorState: any; onChange: (editorState: any) => void; keyBindingFn: (e: any) => "enter" | "undo" | "redo" | "delete" | "delete-word" | "backspace" | "backspace-word" | "backspace-to-start-of-line" | ... 10 more ... | "secondary-paste"; plugins: any[]; placeholder: string; ref: (element: PluginEditor)...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.ts(2322)
```

To reproduce this in typescript:

```bash
yarn add draft-js-plugins-editor @types/draft-js
```

```typescript
import Editor from "draft-js-plugins-editor"

<Editor
  id={`composer-id-${isEdit ? message.id : "main"}`} // error 1
  editorState={this.state.editorState} // error 2
  onChange={this.onChange}
  keyBindingFn={this.keyBindingFn}
  plugins={this.plugins}
  placeholder={"Write comment..."}
  ref={(element) => { this.editor = element }}
/>
```

Downgraded to `v2.1.1` for now.

**Comment by Iliyass** [comment]
I had the same issue, but I fixed it.
Typescript was complaining about those props because they didn't exist on `PluginEditorProps` interface, but `PluginEditorProps` was extending from `EditorProps` which is a draft-js interface, but Typescript couldn't find it because`@types/draft-js` wasn't installed, once I installed it, Typescript stops complaining about those props.

**Solution**:
`yarn add @types/draft-js`

**Comment by gencer** [comment]
Nope. Not in my case. When both installed, my environment complains about it as my first post. Here is full output:

```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<PluginEditorProps>): PluginEditor', gave the following error.
    Type '{ id: string; editorState: any; onChange: (editorState: any) => void; keyBindingFn: (e: any) => "code" | "redo" | "undo" | "bold" | "italic" | "strikethrough" | "underline" | "delete" | "enter" | ... 9 more ... | "secondary-paste"; plugins: any[]; placeholder: string; ref: (element: PluginEditor) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.
      Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.
  Overload 2 of 2, '(props: PluginEditorProps, context?: any): PluginEditor', gave the following error.
    Type '{ id: string; editorState: any; onChange: (editorState: any) => void; keyBindingFn: (e: any) => "code" | "redo" | "undo" | "bold" | "italic" | "strikethrough" | "underline" | "delete" | "enter" | ... 9 more ... | "secondary-paste"; plugins: any[]; placeholder: string; ref: (element: PluginEditor) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.
      Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PluginEditor> & Readonly<PluginEditorProps> & Readonly<{ children?: ReactNode; }>'.ts(2769)
```
